### ISSUE TITLE
WordPress Plugin Update

### ISSUE THREAD

**Issue by vanndigitalnetworks** [robflaherty/scroll-depth#122]
What's going on,

I'd like to say that the WordPress plugin is a good plugin. With that in mind, will it be updated anytime soon??? Let me know 👍🏾

**Comment by robflaherty** [comment]
Hi - The WP plugin was created by @schnoggo. I'm not sure if it's still maintained. Google Tag Manager now offers basic scroll depth tracking natively so there's less need for these plugins.

**Comment by schnoggo** [comment]
Correct, @robflaherty.
I'm not updating since it's now built into Google Analytics.
